-- =========================
-- TABLE: accounts
-- =========================
CREATE TABLE accounts (
    id          VARCHAR2(1024) PRIMARY KEY,
    email       VARCHAR2(1024) NOT NULL,
    password    VARCHAR2(1024) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- =========================
-- TABLE: rooms
-- =========================
CREATE TABLE rooms (
    id          VARCHAR2(1024) PRIMARY KEY,
    name        VARCHAR2(1024) NOT NULL,
    owner_id    VARCHAR2(1024) NOT NULL,
    owner_type  VARCHAR2(1024) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_rooms_owner
        FOREIGN KEY (owner_id)
        REFERENCES accounts(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_rooms_owner_id ON rooms(owner_id);

-- =========================
-- TABLE: room_members
-- =========================
CREATE TABLE room_members (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     VARCHAR2(1024) NOT NULL,
    account_id  VARCHAR2(1024) NOT NULL,
    role        VARCHAR2(50) DEFAULT 'member' NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_room_members_room
        FOREIGN KEY (room_id)
        REFERENCES rooms(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_room_members_account
        FOREIGN KEY (account_id)
        REFERENCES accounts(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_room_members_room_id ON room_members(room_id);
CREATE INDEX idx_room_members_account_id ON room_members(account_id);

-- Optional: 1 account only join 1 room once
CREATE UNIQUE INDEX uq_room_members_room_account
ON room_members(room_id, account_id);
